postgres:
  host: 192.168.5.60
  port: 30432
  dbname: crater
  user: postgres
  password: DcNuWzUh0kI2k7tZSl3Uf84LwDm0cRMSWqwcYtTbgK35g56rjenpXfUzOjy7N0zz
  sslmode: disable
  TimeZone: Asia/Shanghai
userSpacePrefix: sugon-gpu-home-lab
accountSpacePrefix: crater-accounts
publicSpacePrefix: sugon-gpu-incoming
auth:
  accessTokenSecret: access_token_secret
  refreshTokenSecret: refresh_token_secret
